version: "3.8"

services:
  mypostgresdb:
    image: postgres:bullseye
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - mypostgresdb
    image: registry.gitlab.com/vasudevan.ajay/spring-postgres-reactive/reactive-postgresql:1.0.1
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.r2dbc.url"  : "r2dbc:postgres://mypostgresdb:5432/postgres",
        "spring.r2dbc.username" : "postgres",
        "spring.r2dbc.password" : "mypostgrespassword"
      }'
    stdin_open: true
    tty: true

volumes:
  db: